### ISSUE TITLE
ADA compliance issue: <object/> element is swipe-able

### ISSUE THREAD

**Issue by nodeEnthu** [wnr/element-resize-detector#105]
I came across an issue where the 
```<object tabindex="-1" type="text/html" data="about:blank" style="display: block; position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; border: none; padding: 0px; margin: 0px; opacity: 0; z-index: -1000; pointer-events: none;"></object>```
becomes swipe-able using google talkback. Is there a way we can add `aria-hidden=“true”` attribute to the element

**Comment by wnr** [comment]
Absolutely! Would you like to create a PR?

**Comment by nodeEnthu** [comment]
cool .. let me give it a go ... thanks

**Comment by nodeEnthu** [comment]
here you go https://github.com/wnr/element-resize-detector/pull/106

**Comment by nodeEnthu** [comment]
@wnr .. could you please create a release with that fix

**Comment by wnr** [comment]
Release as 1.1.15 now. Thanks for the contribution!
