### ISSUE TITLE
erd.listenTo() always fires initially?

### ISSUE THREAD

**Issue by pmorch** [wnr/element-resize-detector#110]
I was expecting `listenTo(elem, func)` to fire only when elem gets resized ; when the size _changes_ from its initial size.. But it seems that as soon as one starts listening, an initial call to `func` is always made, as demonstrated in this [codesandbox](https://codesandbox.io/s/element-resize-detector-init-fires-iu3om) where we start listening on a div that has long since settled in to a stable state and size, but the callback gets called anyway.

Is this on purpose? Is it _guaranteed_? If I can _rely_ on that, then I can arrange to discard the very first call to the callback with a `if (numCalls++ > 0)` thingy. But I'd like to know if there are some corner cases / race coditions  (e.g. in some browsers?) where it isn't safe to ignore the initial callback.

I suggest one of these:

1. Document this behavior, including any gotchas and/or corner cases
1. Perhaps allow an option to avoid the first, initial call
1. Acknowledge this as a bug and remove the initial call

I guess 3. isn't going to happen for backwards-compatibility reasons...

If you decide against doing anything for this issue, I'm fine with just closing this issue, but I'm hoping I at least can rely on this behavior or learn the reasoning behind it. I find it odd that the callback gets called immediately in the codesandbox above.

**Comment by wnr** [comment]
Hi and thanks for the comment. The behavior is per design and guaranteed. I agree that it should be better documented. I'll try and do this ASAP. I think there is an option you can pass to the function named "callOnAdd".

**Comment by pmorch** [comment]
Thanks!

    this.erd = elementResizeDetectorMaker({
        strategy: "scroll", //<- For ultra performance.
        callOnAdd: false,
    });

Worked like a charm, exactly as expected.

Ironically, in `src/element-resize-detector.js`, `strategy` is not documented, but `callOnAdd` _is_, along with several others. As opposed to `README.md`, where `strategy` is the only documented option.

So We can cross out 2. from my list. Now only 1. is left... :-) Thanks!

**Comment by wnr** [comment]
Great! I've documented it now.

**Comment by pmorch** [comment]
Documented in 2fcd1055641ab6d8fec22b26aaa56bc65b29bb4e
