### ISSUE TITLE
Resize not reported for particular case where listener element is in flex layout

### ISSUE THREAD

**Issue by jeffmath** [wnr/element-resize-detector#111]
Please see [this Plunker](https://plnkr.co/edit/D2RYzdgwMD7S6GqUl3Hv).  It is based on one of your examples, but partially replicates the UI of a component in an app my team is developing.

Note how the reported width stays the same after resizing the window.  However, if the display style of the first `div` is changed to `block`, the reported width changes with each resize.  Also, if you instead remove the `div` with the explicitly specified size (or, just remove the size), the reported width changes with each resize.

Is this a bug, or is it a case your package is not designed to handle?

**Comment by wnr** [comment]
HI and thanks for the question. You are not getting any resize events since the element you are listening to does not change size when you resize the window. If you want the element to resize you'll need to review your layout.
