### ISSUE TITLE
'window' is not defined in SSR

### ISSUE THREAD

**Issue by wilfredmifsud** [wnr/element-resize-detector#112]
Hi

While testing your plugin (through [ngx-ellipses](https://github.com/lentschi/ngx-ellipsis)), I am encountering an issue where a `window is not defined` error is showing while rendering the website in SSR.

From what I can see you have no checks if the `window` exists in the current context.

It currently shows the text "undefined" instead of the actual text.

![image](https://user-images.githubusercontent.com/739777/66922273-059bd400-f027-11e9-93bb-c44e531121d5.png)

I would really like it to work somehow in SSR and non-SSR version of the website.

Any help would be great

**Comment by benheb** [comment]
What was the solution here?
