### ISSUE TITLE
use ResizeObserver API when available

### ISSUE THREAD

**Issue by lpillonel** [wnr/element-resize-detector#114]
Any plan to use ResizeObserver when available ? 
[Currently supported by Chrome & Firefox.](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver)

**Comment by wnr** [comment]
That's a great idea. Would you like to create a PR?

**Comment by gilest** [comment]
Looks like an implementation is [arriving in webkit](https://webkit.org/blog/9997/resizeobserver-in-webkit/) too!

**Comment by wnr** [comment]
That's great! I've actually changed my mind. I think there should be a polyfill project, which could use this library as a fallback if the API does not exist natively. That way this library could get phased out in a smoother way.
