### ISSUE TITLE
Scrollbars go out of sync when using animation

### ISSUE THREAD

**Issue by miiihi** [wnr/element-resize-detector#116]
I've a rather corner case, that I can't replicate in a simple Plunker - I tried, but there it works as expected.
I have an Angular app, with a Angular Material Expansion Panel. Opening/Closing  the expansion panel causes a sibling element to change size (which I want to observe), but resize detector is not detecting changes...

Debugging shows following:
- scroll event fires, but there is no change in size of element (yet), but there is a change in expandElement.scrollTop which is 0.
- no further scroll events are fired.
- if I disable all Angular animations, everything works as expected.

I've prepared a fix, which is quite simple - just adding a check for scrollbars out of sync in the handleScroll method, see #115 

Hopefully you can merge PR, even without replicable issue.
Thanks

**Comment by wnr** [comment]
Hi @miiihi and thank you for your PR. It looks good to me, but I'm generally very reluctant to modifying the code without properly understanding why. Stability and performance is key for this lib, so I hope you understand my concerns. Could you perhaps give it another go to find a replicable case? I would much appreciate it.

Kind Regards, and merry xmas!
