### ISSUE TITLE
Console warning violations in Chrome `Forced reflow while executing JavaScript`

### ISSUE THREAD

**Issue by alexdiliberto** [wnr/element-resize-detector#124]
Noticed some Chrome console warnings when running in my application and traced back to this library's `getScrollbarSizes` method on the line `var widthSize = width - container.clientWidth;`

```
[Violation] Forced reflow while executing JavaScript took 100ms
```

<img width="244" alt="Screen Shot 2020-06-24 at 4 14 17 PM" src="https://user-images.githubusercontent.com/666459/85623063-c736ca00-b635-11ea-9eab-c48820426888.png">

<img width="472" alt="Screen Shot 2020-06-24 at 4 10 53 PM" src="https://user-images.githubusercontent.com/666459/85622886-88087900-b635-11ea-810a-de17de0bfc2d.png">

<img width="398" alt="Screen Shot 2020-06-24 at 4 11 17 PM" src="https://user-images.githubusercontent.com/666459/85622876-85a61f00-b635-11ea-9526-28e5b9b93a19.png">

**Comment by wnr** [comment]
Yeah can't really do much about that :/

**Comment by ghost** [comment]
why not use default strategy object?

**Comment by wnr** [comment]
Because default strategy supports more legacy browsers, including even IE6.
