### ISSUE TITLE
Scroll detection strategy does not work within a shadow root

### ISSUE THREAD

**Issue by mupchrch** [wnr/element-resize-detector#127]
[This line](https://github.com/wnr/element-resize-detector/blob/master/src/detection-strategy/scroll.js#L176) doesn't account for the situation where the element resides within a shadow root. Debug is reporting the element is detached.

I think a check like `element.getRootNode().contains(element)` could be added here to account for this issue? Not sure which browsers you are targeting to support - might be important to note `getRootNode` is not supported in IE.

**Comment by wnr** [comment]
@mupchrch Interesting! Yeah, this lib is targeting IE6 😓 . But we could probably just check if getRooNode exists and consider it a new feature upgrade if it does. Would you like to create a PR for this? :)

**Comment by mupchrch** [comment]
@wnr Not to be a bother.. When can we expect to see v1.2.2 released on npm?

**Comment by wnr** [comment]
@mupchrch Sorry 'bout that! It's now published. Thank you for reminding me :) Have a great weekend!
