### ISSUE TITLE
I want to ask what problems will occur if the code here is deleted

### ISSUE THREAD

**Issue by w934423231** [wnr/element-resize-detector#135]
![image](https://user-images.githubusercontent.com/38958128/195818690-8d2b16ba-2f1e-432f-bc7b-703f35c3a4e4.png)
The code here conflicts with the process of my code, so I need to delete it. I wonder if there will be any unexpected problems after I delete it

**Comment by wnr** [comment]
Depending on your global styles, the system might break.
