### ISSUE TITLE
State purity in tests

### ISSUE THREAD

**Issue by m59peacemaker** [wnr/element-resize-detector#24]
I suggest creating and appending a new element for each test.. is there some magic going on that takes care of that, or are all the tests using the same DOM/state ? I have limited experience with Jasmine/Karma (I use [tape](https://www.npmjs.com/package/tape)), so I might be missing something. If each test is reusing the same element, I'd be glad to submit a PR to improve this. I think the Jasmine way is to use `beforeEach()`, though I personally prefer to skip the magic and manually call functions I need per test. Tell me what you think and I'll see if I can help.

**Comment by wnr** [comment]
I agree with every single statement.

A PR would be awesome :)

**Comment by wnr** [comment]
Do you still want to submit a PR for this @m59peacemaker? Otherwise I'm looking to close this issue :)

**Comment by m59peacemaker** [comment]
I don't have the time :/ It's not needed anyway.

**Comment by wnr** [comment]
Okay, thanks anyway :)
