### ISSUE TITLE
Seems like when calling listenTo, only the first function will be added to the object resize event listener.

### ISSUE THREAD

**Issue by wnr** [wnr/element-resize-detector#4]
Can be solved by having only one function applied to the object, which calls all listeners

**Comment by asurabhi** [comment]
IMO this should be fixed in the library. I am using this in react where the suggested solution is not easy.

**Comment by wnr** [comment]
Could you give me more information how this affects you? This should only be an implementation detail of the library, all functions you attach to listenTo should be called (see test case https://github.com/wnr/element-resize-detector/blob/master/test/element-resize-detector_test.js#L149). Is this not the case?
