### ISSUE TITLE
Scroll detection element sometimes causing page-level scrollbars

### ISSUE THREAD

**Issue by AntonTrollback** [wnr/element-resize-detector#40]
Can happen when the ERD enabled element is positioned close to the page boundaries.

Fixed by wrapping `.erd_scroll_detection_container` with something like this:
```
<div style="overflow: hidden; position: absolute; top: 0; right: 0; bottom: 0; left: 0">
  ... 
</div>
```
Should probably be tested that it doesn't cause new issues.

**Comment by wnr** [comment]
Fixed in version 1.1.0 ;)
