### ISSUE TITLE
Is it safe to remove element without remove handler ?

### ISSUE THREAD

**Issue by zhaoyao91** [wnr/element-resize-detector#42]
Is it safe to remove element without remove handler ?
In some cases, the element is removed without any chance to remove listeners. will this cause any problem like memory leaking?

**Comment by wnr** [comment]
Yes, since all listeners are attached to the element itself it should get garbage collected when removed from the DOM. We too remove the elements freely, and haven't noticed any problems.

**Comment by zhaoyao91** [comment]
thanks
