### ISSUE TITLE
requiring source into my own JS (also using browserify) causes "cannot find module error"

### ISSUE THREAD

**Issue by jsdw** [wnr/element-resize-detector#48]
see https://github.com/substack/node-browserify/issues/374

one suggestion was to use "derequire" eg so you'd end up with:

`browserify main.js --standalone Foo | derequire > bundle.js`

as a note, there is no issue with your minified build (since the "require" function is renamed anyway)

**Comment by wnr** [comment]
I might misunderstand you, but shouldn't you simply `require('element-resize-detector')` in your code? This way, you won't use the minified UMD build in `dist/`.

**Comment by wnr** [comment]
As I believe this is not an issue with this project, I'll close this issue. Please feel free to reopen if you believe it is.
