### ISSUE TITLE
uninstall throws - Cannot read property 'busy' of undefined

### ISSUE THREAD

**Issue by justintfrost** [wnr/element-resize-detector#50]
When calling the uninstall method on a erd the above error is thrown.

```
var resizeDetectorElements = $("#uid .container").toArray();
var resizeDetector = elementResizeDetectorMaker({
	 strategy: "scroll" //<- For ultra performance.
});
resizeDetector.listenTo(resizeDetectorElements, function(element) {
	// code for resize
});

*** this line throws the error ***
resizeDetector.uninstall(resizeDetectorElements);
```

**Comment by wnr** [comment]
Hi and thanks for the issue. The uninstall API takes a single element as input, so it throws an error when you pass it an array. I think it would be a nice addition to the method to also accept an array, I'll look into that.

Thanks

**Comment by eliseumds** [comment]
That happens when hot reload happens as well (React).

**Comment by wnr** [comment]
@eliseumds I see. Thanks for the PR. As I believe this is another issue (calling uninstall on already uninstalled elements) I'll not close this issue, but happily merge the PR :)

**Comment by eliseumds** [comment]
@wnr you're right, that's different, sorry =S  I updated the commit msg on #52

**Comment by wnr** [comment]
@eliseumds No problems at all :) I have merged your PR locally, and will publish it soon. Looking to fix this issue at the same time.

**Comment by wnr** [comment]
Support for multiple elements is now supported in v1.1.3.
