### ISSUE TITLE
onShrink attempted on undefined object

### ISSUE THREAD

**Issue by prasannavl** [wnr/element-resize-detector#54]
During certain manual stress tests, I ended up with the following error.

`main.9f41ae4….js:16 Uncaught TypeError: Cannot read property 'onShrink' of undefined`

Unfortunately, it was a production system I was testing, so I just narrowed it down to this library, and the location of the minimized code looks something like this:

`O(w,"scroll",function(){c(e).onShrink&&c(e).onShrink()})}`

which leads to this line on the scroll detection strategy file: https://github.com/wnr/element-resize-detector/blob/master/src/detection-strategy/scroll.js#L370

So, probably a scroll event executed even the element's state is invalid. I'm unsure on when exactly that happened, due to the nature of my tests. However, I'm certain enough to file this issue (I'm using the resizer at only one point in the whole application, and it properly disposes of its resources, so its not from the app directly, but just likely just sets it up for this bug).

**Comment by wnr** [comment]
Hi, and thanks for the report.

It seems to me that the state property of the element has been manually removed, which results in that when the scroll event is executed the `element._erd` property is missing. Perhaps your app is altering the element in some way that removes the property?

**Comment by prasannavl** [comment]
Hi. That makes sense. 

My component was rendered using React, and once rendered the scroll sensor is initialized and disposed off as necessary as it updated. However, only later did I realize I had an edge case, where the resize sensor was setup in a nested component deeper down the tree which was managed by another react component. So, as the inner one updated, it re-rendered the tree which constituted of the sensor, causing the problem. 

My bad. Thanks for your time pointing me in the right direction! :)

**Comment by wnr** [comment]
Okay, great :) No problems, I'm happy to help.
