### ISSUE TITLE
Mixed content

### ISSUE THREAD

**Issue by tregusti** [wnr/element-resize-detector#57]
In Chrome Canary (53 and 54) I now get this warning for each element that has a listener for resizes:

![](http://i.imgur.com/fqkg68Q.png)

I am using v1.1.0 and are not sending in any options to `elementResizeDetectorMaker`.

Using the site in stable Chrome 51 gives no such error.

**Comment by wnr** [comment]
Ah, interesting. I can take a look, but keep in mind that the default `object` strategy has been deprecated and will not be supported much longer. I strongly suggest you to switch to using the `scroll` approach.

**Comment by wnr** [comment]
I've tried to fix this issue, but it seems hard. I won't put more effort into this issue as the object approach is deprecated. I would happily accept a PR if someone manage to fix this.

**Comment by wnr** [comment]
Closing this issue as it won't be fixed, and the object solution is deprecated.
