### ISSUE TITLE
Add flex 0 to container styles

### ISSUE THREAD

**Issue by souporserious** [wnr/element-resize-detector#64]
This can totally be done in a stylesheet, but how do you feel about adding `flex: 0` into the `containerContainer` inline styles? https://github.com/wnr/element-resize-detector/blob/master/dist/element-resize-detector.js#L793

**Comment by wnr** [comment]
That seems reasonable :) I would accept such PR.

**Comment by souporserious** [comment]
Awesome :) I'll get it together as soon as I can.

**Comment by wnr** [comment]
Sounds great!

**Comment by wnr** [comment]
This is now fixed in version 1.1.10

**Comment by souporserious** [comment]
Thanks!
