### ISSUE TITLE
Object is focusable with tab

### ISSUE THREAD

**Issue by octocode** [wnr/element-resize-detector#67]
Would it be possible to add

`object.tabIndex = -1;`

**Comment by wnr** [comment]
Yes, that should work. I'll accept such PR, or do it myself in the near future. However, please note that the object approach is deprecated (use the scroll approach instead).

**Comment by ioquatix** [comment]
When will scroll approach become the default?

**Comment by wnr** [comment]
In the next major bump (2.0.0). Please note that there is no planned major bump at this time, as I do not want to bump major just for the default value of the strategy option. If something bigger in the future needs to bump major, I'll change the default value at the same time.

**Comment by wnr** [comment]
The object tab index issue is now fixed in release 1.1.10
