### ISSUE TITLE
getComputedStyle firefox, question

### ISSUE THREAD

**Issue by SeeThruHead** [wnr/element-resize-detector#68]
I'm having an issue using your library in firefox. Seem to be that in my application getComputedStyle(element) inside scroll.js returns null in firefox. I assume this is my fault somehow but am unable to pinpoint how. Was hoping you might have some insight.

**Comment by SeeThruHead** [comment]
i think it is related to this
https://bugzilla.mozilla.org/show_bug.cgi?id=795520
i am rendering inside an iframe.

**Comment by wnr** [comment]
Hmm that is really interesting! I haven't noticed any similar issues, so I guess you are on the right track regarding rendering inside an iframe. Would it be possible for you to share a minimal jsfiddle displaying the problem?

**Comment by wnr** [comment]
I'm going to close this. Please reopen if you have a minimal example that displays the problem.

**Comment by xaviervia** [comment]
Please let's reopen this. Here is the example:

https://example-get-computed-style-failing-rybndfgpil.now.sh/ <- failing
https://example-get-computed-style-failing-rybndfgpil.now.sh/iframe.html <- what it should be

**The content of the iframe**
As you can see in the console, it logs the contents:

<img width="876" alt="screen shot 2017-03-30 at 14 13 28" src="https://cloud.githubusercontent.com/assets/381614/24503606/14fcd2e8-1553-11e7-892c-41d4da43e690.png">

**On a hidden iframe**
If logs `null` in the console.

<img width="876" alt="screen shot 2017-03-30 at 14 13 38" src="https://cloud.githubusercontent.com/assets/381614/24503605/14f5492e-1553-11e7-934d-a5faf1931b7c.png">

**Comment by wnr** [comment]
Thank you for the information, I'll analyze this asap.

**Comment by xaviervia** [comment]
No worries. Let me know if I can be of any help.

**Comment by wnr** [comment]
I have now pushed a fix in the develop branch. Could you try it out?

**Comment by wnr** [comment]
Did you get any chance to try this out? It seems to work fine for me with the fix in the develop branch.

**Comment by wnr** [comment]
Fix released in 1.1.12.

**Comment by xaviervia** [comment]
Hi! I'm sorry I was out on vacations when this happened. Thanks a lot for fixing it! I will make sure to update soon :)
