### ISSUE TITLE
Event listener is firing too liberally

### ISSUE THREAD

**Issue by alvinwoon** [wnr/element-resize-detector#70]
Merely clicking on a div will dispatch an event within listenTo. Actually loading the page will fire the event as well.

**Comment by wnr** [comment]
Hi and thanks for the report. I'll look into this asap. If you wish to help, a test case or similar would be much appreciated :)

**Comment by wnr** [comment]
> Merely clicking on a div will dispatch an event within listenTo.

I fail to reproduce this. Which browser and OS? Any special circumstances?

> Actually loading the page will fire the event as well.

Have you seen the `callOnAdd` option? Setting it to `false` should prevent the first event to fire.

**Comment by alvinwoon** [comment]
`callOnAdd` fixed the problem. Thanks! Didn't realize there was such option.

**Comment by wnr** [comment]
Great! :)
