### ISSUE TITLE
dist file cannot be minified with babili

### ISSUE THREAD

**Issue by rosskevin** [wnr/element-resize-detector#71]
In the `dist/element-resize-detector.js`, it runs [`var browserDetector = require("../browser-detector");`](https://github.com/wnr/element-resize-detector/blob/master/dist/element-resize-detector.js#L235).

I tracked this down because when minifying with `babili`, it fails here with something like `Uncaught ReferenceError: G is not defined`. 

This correlates to source in `detection-strategy/object.js`.

I'm unfamiliar with browserify, otherwise I would submit a PR.  It's certainly possible I'm wrong here, but I have tracked it to this package via obfuscated code:

```javascript
        , function(V) {
            "use strict";
            var Y = V.exports = {};
            Y.getOption = G            // Uncaught ReferenceError: G is not defined
        }
        , function(V, Q, G) {
            "use strict";
            var Y = G(1);
            V.exports = function(X) {
                function ee(le) {
                    return ne(le).object
                }
                X = X || {};
                var oe = X.reporter
                  , ae = X.batchProcessor
                  , ne = X.stateHandler.getState;
                if (!oe)
                    throw Error("Missing required dependency: reporter.");
                return {
                    makeDetectable: Z,
                    addListener: J,
                    uninstall: function(le) {
                        Y.isIE(8) ? le.detachEvent("onresize", ne(le).object.proxy) : le.removeChild(ee(le)),
                        delete ne(le).object
                    }
                }
            }
        }
```

This is a show-stopper for my production code, I hope someone can look at this soon.  If not, please let me know.

**Comment by rosskevin** [comment]
This code from the dist file may be what it is referring to, it's the only `*.getOption = `

```javascript
{"./utils":2}],2:[function(require,module,exports){
"use strict";

var utils = module.exports = {};

utils.getOption = getOption;

function getOption(options, name, defaultValue) {
    var value = options[name];

    if((value === undefined || value === null) && defaultValue !== undefined) {
        return defaultValue;
    }

    return value;
}
```

**Comment by rosskevin** [comment]
Just found something strange, `function getOption` is found twice in the dist file.  Once in the `./utils` above and once in global scope.

**Comment by rosskevin** [comment]
So it seems that `getOption` is something injected by browserify.  In keeping this code explicit, I'm trying to rename the local function to see if that works with babili.  Quite strange.

**Comment by rosskevin** [comment]
So, in my experiment, I renamed the local `getOption` to `resolveOption` and imported it from another file just so it was easier to see the separation in the obfuscated output.  

The code still fails to minify with babili on the same spot, which I take it refers to the injected browserify code:

```javascript
        , function(V) {
            "use strict";
            var Y = V.exports = {};
            Y.getOption = G                 // Uncaught ReferenceError: G is not defined
        }
```

@wnr any thoughts about updating dependencies (they are pretty old) and perhaps transitioning this to a simple babel library build?

**Comment by wnr** [comment]
Hi @rosskevin and thank you for the awesome issue! Sorry that I'm responding so late. I'll start experimenting myself, and read through your findings more in detail later tonight :)

I'm very interested in updating the dependencies, and would love some help with that 👍

**Comment by rosskevin** [comment]
FYI - this does minify with Uglify, so not sure if this is an actual bug with the dist file or not, but I have linked the issue with babili so we can figure it out.  The response there will probably dictate what I do from here as I'd rather use babili, but uglify is so far working.

**Comment by wnr** [comment]
Okay, thanks for the input. I'll start working on updating the build step in the mean time.

**Comment by wnr** [comment]
I'm going to close this. Please reopen if your the conclusion is that there's something wrong at this end.
