### ISSUE TITLE
TypeScript Definition

### ISSUE THREAD

**Issue by jinder** [wnr/element-resize-detector#76]
Any chance of shipping a TS definition with the library?  Definition below (adapted from [SO](http://stackoverflow.com/questions/41027750/use-element-resize-detector-library-in-an-angular2-application)):

```
declare interface ErdmOptions {
  strategy?: "scroll" | "object";
}

declare interface ElementResizeDetector {
  listenTo<T extends HTMLElement>(element: T, callback: (elem: T) => void): void;
  removeListener<T extends HTMLElement>(element: T, callback: (elem: T) => void): void;
  removeAllListeners(element: HTMLElement): void;
  uninstall(element: HTMLElement): void;
}

declare module "element-resize-detector" {
  const elementResizeDetectorMaker: (options?: ErdmOptions) => ElementResizeDetector;

  export = elementResizeDetectorMaker;
}

```

**Comment by wnr** [comment]
No sorry. Perhaps a project `element-resize-detector-ts` or similar can be created to support this (similar to the ember/angular/react/vue/etc versions of this project). I don't like the idea of this project supporting the union of all frameworks/languages that web developers use.

**Comment by saranshkataria** [comment]
Have created a @types definition for this: https://www.npmjs.com/package/@types/element-resize-detector
