### ISSUE TITLE
ResizeObserver polyfill?

### ISSUE THREAD

**Issue by ZeeCoder** [wnr/element-resize-detector#78]
Out of curiosity, would it be hard to turn this solution to a ResizeObserver polyfill?
I'm working on a Container Query solution, and I like the idea of handling element size changes in a batch, as described here: https://github.com/que-etc/resize-observer-polyfill

For this reason I was leaning more towards this solution: https://github.com/que-etc/resize-observer-polyfill
Until I read that it takes ~20ms for a resize change to register.
I'm hopeful that this library would do better than that, but at the same time, I like the other interface better.

**Comment by wnr** [comment]
Hi,

Surely it would be easy to put another API on top of the current API, it should be pretty straight forward. As a side note, this library is batching everything possible but also has around ~20ms penalty when detecting changes (I think this is as low as it can be).

If you like the other interface better feel free to create a new project with that API that uses this library as an implementation. Or use the other project you linked to :)

Cheers

**Comment by ZeeCoder** [comment]
Yeah I was thinking about doing that. :+1:

Cheers

**Comment by andreiglingeanu** [comment]
Or just do something like this:

```javascript
	if (window.ResizeObserver) {
		const ro = new ResizeObserver((entries, observer) =>
			setHeightFor(footer)
		)

		ro.observe(footer)
	} else {
		erd().listenTo(footer, () => setHeightFor(footer))
	}
```

Of course it's very easy to extract a common interface out of this but it looks good enough for me at this moment.
