### ISSUE TITLE
Adding listener repositions elements to origin that use translate inside SVG

### ISSUE THREAD

**Issue by hanvyj** [wnr/element-resize-detector#79]
I've got a html element inside a foregnObject tag of an SVG and I've found a bug where anything that has the listener added is rendered at the origin.

Here's a demo of the behavior:

https://plnkr.co/edit/whWckDZfNGRyYKPF89FF?p=preview

Notice the element still thinks it's positioned where it should be, it seems to just be the rendering of the element that is affected. Notice if you hover over it in the debugger it highlights the wrong area:

![image](https://cloud.githubusercontent.com/assets/20140222/26365071/6ac0f686-3fde-11e7-9bb9-3f4b28811980.png)

**Comment by wnr** [comment]
Hi, and thanks for the report. That's interesting. The same behavior is achieved without this library, by adding `position:relative` to the div. I don't know why the browser behaves like that in such circumstances, it seems like a browser bug to me. FireFox handles it just fine, but Safari and Chrome does not so I guess it's Webkit-based. Perhaps you could file a bug over at webkit?

Unfortunately, there's I cannot think of any way to work around the relative positioning in this library. So I guess we have to wait until Webkit fixes it.

**Comment by hanvyj** [comment]
Yeah, you're right​, didn't spot it did the same for position: relative. Looks like a 6+ year old bug with webpack. So I'm not confident it'll be fixed any time soon!

http://stackoverflow.com/questions/8185845/svg-foreignobject-behaves-as-though-absolutely-positioned-in-webkit-browsers

Thanks for giving me the general issue so I can search for workarounds though.

**Comment by wnr** [comment]
Too bad about the bug not being fixed yet. No problems, always glad to help :)

Cheers
