### ISSUE TITLE
Error: Element is not detectable by this strategy

### ISSUE THREAD

**Issue by alexjlockwood** [wnr/element-resize-detector#81]
This may not be a bug in the library... might be an issue on my part.

I've gotten an error report from a user with the below trace. I tried looking at the source code but wasn't certain about when the error actually occurs. The user and I are both using the latest version of Chrome 59 and yet I'm unable to reproduce the issue myself.

Is there any particular reason why this error would be thrown and are there any obvious ways that it can be avoided? 

```
vendor.d62c677178de6bb28515.bundle.js:8 ERROR Error: Element is not
detectable by this strategy.
    at Object.e [as addListener] (vendor.d62c677178de6bb28515.bundle.js:331)
    at vendor.d62c677178de6bb28515.bundle.js:331
    at vendor.d62c677178de6bb28515.bundle.js:331
    at r (vendor.d62c677178de6bb28515.bundle.js:331)
    at HTMLObjectElement.s (vendor.d62c677178de6bb28515.bundle.js:331)
    at HTMLObjectElement.o [as __zone_symbol___onload]
(polyfills.941f119dea8a6d6529f8.bundle.js:8)
    at t.invokeTask (polyfills.941f119dea8a6d6529f8.bundle.js:36)
    at Object.onInvokeTask (vendor.d62c677178de6bb28515.bundle.js:153)
    at t.invokeTask (polyfills.941f119dea8a6d6529f8.bundle.js:36)
    at r.runTask (polyfills.941f119dea8a6d6529f8.bundle.js:36)
v @ vendor.d62c677178de6bb28515.bundle.js:8
```

It seems like the crash is happening on this [line of code](https://github.com/wnr/element-resize-detector/blob/master/src/detection-strategy/object.js#L28), which is being called as a result of a call I am making to `erd.listenTo(element, callbackFn)` [here](https://github.com/alexjlockwood/ShapeShifter/blob/107aa3afac2a9cf0357b5c1463f1359301197ec4/src/app/components/root/root.component.ts#L130). The element I am trying to listen to is [here](https://github.com/alexjlockwood/ShapeShifter/blob/107aa3afac2a9cf0357b5c1463f1359301197ec4/src/app/components/root/root.component.html#L26).

(IDK if any of that info is helpful, but just thought I would be as detailed as I could).

**Comment by joerogers** [comment]
FYI, I'm the user in question: I'm on Chrome 59.0.3071.104 and MacOS version 10.12.5 if that helps anything.

**Comment by wnr** [comment]
Hi, and thanks both of you for the information. You are using the object-strategy, which is way less popular than the scroll-strategy. May I suggest trying the scroll-strategy and see if the problem still occurs? You do so by passing "scroll" to the "strategy" option to the constructor, like so:

```
var erd = elementResizeDetectorMaker({
  strategy: "scroll"
});
```

**Comment by alexjlockwood** [comment]
Will do, I just published an update with the change. @joerogers LMK if you see any difference (you might need to CMD + SHIFT + R to clear the cache).

**Comment by joerogers** [comment]
The fix seems to have solved the issue I was having. Thanks @alexjlockwood

**Comment by alexjlockwood** [comment]
Great! :)

I'll leave it up to @wnr if he wants to close the issue. But seems like that must have been the problem. Thanks for the suggestion!

**Comment by wnr** [comment]
Awesome!

I'll see if there's anything I can do about this problem regarding the object strategy. I've found issues before with Chrome that was unresolvable. That's why I deprecated this strategy, but I did not want to break the current API. But it is great that the scroll strategy fixed it for you guys :)
